// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createOneGoal = `-- name: CreateOneGoal :one
INSERT INTO goals (user_id, title, difficulties)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, difficulties, created_at
`

type CreateOneGoalParams struct {
	UserID       uuid.UUID
	Title        string
	Difficulties json.RawMessage
}

func (q *Queries) CreateOneGoal(ctx context.Context, arg CreateOneGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createOneGoal, arg.UserID, arg.Title, arg.Difficulties)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Difficulties,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGoalByID = `-- name: DeleteGoalByID :one
DELETE FROM goals
WHERE id = $1
    AND user_id = $2
RETURNING id
`

type DeleteGoalByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteGoalByID(ctx context.Context, arg DeleteGoalByIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteGoalByID, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT id, user_id, title, difficulties, created_at FROM goals
WHERE id = $1
    AND user_id = $2
`

type GetGoalByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetGoalByID(ctx context.Context, arg GetGoalByIDParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoalByID, arg.ID, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Difficulties,
		&i.CreatedAt,
	)
	return i, err
}

const getGoalByUserIDandTitle = `-- name: GetGoalByUserIDandTitle :one
SELECT id, user_id, title, difficulties, created_at FROM goals
WHERE user_id = $1
    AND title = $2
`

type GetGoalByUserIDandTitleParams struct {
	UserID uuid.UUID
	Title  string
}

func (q *Queries) GetGoalByUserIDandTitle(ctx context.Context, arg GetGoalByUserIDandTitleParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoalByUserIDandTitle, arg.UserID, arg.Title)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Difficulties,
		&i.CreatedAt,
	)
	return i, err
}

const getGoalsByUserID = `-- name: GetGoalsByUserID :many
SELECT id, user_id, title, difficulties, created_at FROM goals
WHERE user_id = $1
`

func (q *Queries) GetGoalsByUserID(ctx context.Context, userID uuid.UUID) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, getGoalsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Difficulties,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoalByID = `-- name: UpdateGoalByID :one
UPDATE goals
SET title = $1,
    difficulties = $2
WHERE id = $3
    AND user_id = $4
RETURNING id
`

type UpdateGoalByIDParams struct {
	Title        string
	Difficulties json.RawMessage
	ID           uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) UpdateGoalByID(ctx context.Context, arg UpdateGoalByIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, updateGoalByID,
		arg.Title,
		arg.Difficulties,
		arg.ID,
		arg.UserID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
