// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type EmailToken struct {
	UserID     uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	VerifiedAt sql.NullTime
	CreatedAt  time.Time
	ID         uuid.UUID
}

type OauthAccount struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	CreatedAt      time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
	Revoked   bool
	RevokedAt sql.NullTime
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash sql.NullString
	CreatedAt    sql.NullTime
	Verified     bool
}
