// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type OauthAccount struct {
	ID             int64
	UserID         int64
	Provider       string
	ProviderUserID string
	CreatedAt      time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    int64
	ExpiresAt time.Time
	Revoked   bool
	RevokedAt sql.NullTime
	CreatedAt time.Time
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash sql.NullString
	CreatedAt    sql.NullTime
}
