// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_account.sql

package db

import (
	"context"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO public.oauth_accounts (user_id, provider, provider_user_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, provider, provider_user_id, created_at
`

type CreateOAuthAccountParams struct {
	UserID         int64
	Provider       string
	ProviderUserID string
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, createOAuthAccount, arg.UserID, arg.Provider, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAccountByProviderID = `-- name: GetOAuthAccountByProviderID :one
SELECT id, user_id, provider, provider_user_id, created_at FROM public.oauth_accounts
WHERE provider = $1
    AND provider_user_id = $2
`

type GetOAuthAccountByProviderIDParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetOAuthAccountByProviderID(ctx context.Context, arg GetOAuthAccountByProviderIDParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccountByProviderID, arg.Provider, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}
