// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const getRefreshTokenById = `-- name: GetRefreshTokenById :one
SELECT id, user_id, expires_at, revoked, revoked_at, created_at FROM refresh_tokens
WHERE id = $1
`

func (q *Queries) GetRefreshTokenById(ctx context.Context, id uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenById, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshTokenById = `-- name: RevokeRefreshTokenById :exec
UPDATE refresh_tokens
SET revoked = true,
    revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeRefreshTokenById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenById, id)
	return err
}
