// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO public.tasks (user_id, goal_id, content, type)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, goal_id, content, type, done, done_at, created_at
`

type CreateTaskParams struct {
	UserID  uuid.UUID
	GoalID  uuid.UUID
	Content json.RawMessage
	Type    string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.UserID,
		arg.GoalID,
		arg.Content,
		arg.Type,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalID,
		&i.Content,
		&i.Type,
		&i.Done,
		&i.DoneAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, user_id, goal_id, content, type, done, done_at, created_at FROM public.tasks 
WHERE id = $1
    AND user_id = $2
`

type GetTaskByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalID,
		&i.Content,
		&i.Type,
		&i.Done,
		&i.DoneAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTasksByUserID = `-- name: GetTasksByUserID :many
SELECT id, user_id, goal_id, content, type, done, done_at, created_at FROM public.tasks
WHERE user_id = $1
`

func (q *Queries) GetTasksByUserID(ctx context.Context, userID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoalID,
			&i.Content,
			&i.Type,
			&i.Done,
			&i.DoneAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
