// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createOneUser = `-- name: CreateOneUser :one
INSERT INTO public.users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, created_at, verified
`

type CreateOneUserParams struct {
	Username     string
	Email        string
	PasswordHash sql.NullString
}

func (q *Queries) CreateOneUser(ctx context.Context, arg CreateOneUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createOneUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Verified,
	)
	return i, err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :one
DELETE FROM public.users
WHERE email = $1
RETURNING id
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteUserByEmail, email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, created_at, verified
FROM public.users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Verified,
	)
	return i, err
}

const verifyUserByID = `-- name: VerifyUserByID :exec
UPDATE public.users
SET verified = true
WHERE id = $1
`

func (q *Queries) VerifyUserByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, verifyUserByID, id)
	return err
}
