// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignment.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO public.classroom_assignments (classroom_id, title, description, goal_id, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, classroom_id, title, description, goal_id, created_by, status, created_at, updated_at
`

type CreateAssignmentParams struct {
	ClassroomID uuid.UUID
	Title       string
	Description string
	GoalID      uuid.NullUUID
	CreatedBy   uuid.UUID
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (ClassroomAssignment, error) {
	row := q.db.QueryRowContext(ctx, createAssignment,
		arg.ClassroomID,
		arg.Title,
		arg.Description,
		arg.GoalID,
		arg.CreatedBy,
	)
	var i ClassroomAssignment
	err := row.Scan(
		&i.ID,
		&i.ClassroomID,
		&i.Title,
		&i.Description,
		&i.GoalID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM public.classroom_assignments WHERE id = $1
`

func (q *Queries) DeleteAssignment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAssignment, id)
	return err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, classroom_id, title, description, goal_id, created_by, status, created_at, updated_at FROM public.classroom_assignments WHERE id = $1
`

func (q *Queries) GetAssignmentByID(ctx context.Context, id uuid.UUID) (ClassroomAssignment, error) {
	row := q.db.QueryRowContext(ctx, getAssignmentByID, id)
	var i ClassroomAssignment
	err := row.Scan(
		&i.ID,
		&i.ClassroomID,
		&i.Title,
		&i.Description,
		&i.GoalID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignmentsByClassroom = `-- name: ListAssignmentsByClassroom :many
SELECT id, classroom_id, title, description, goal_id, created_by, status, created_at, updated_at FROM public.classroom_assignments
WHERE classroom_id = $1 AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListAssignmentsByClassroom(ctx context.Context, classroomID uuid.UUID) ([]ClassroomAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listAssignmentsByClassroom, classroomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClassroomAssignment
	for rows.Next() {
		var i ClassroomAssignment
		if err := rows.Scan(
			&i.ID,
			&i.ClassroomID,
			&i.Title,
			&i.Description,
			&i.GoalID,
			&i.CreatedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE public.classroom_assignments
SET title = $2, description = $3, goal_id = $4, updated_at = now()
WHERE id = $1
RETURNING id, classroom_id, title, description, goal_id, created_by, status, created_at, updated_at
`

type UpdateAssignmentParams struct {
	ID          uuid.UUID
	Title       string
	Description string
	GoalID      uuid.NullUUID
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (ClassroomAssignment, error) {
	row := q.db.QueryRowContext(ctx, updateAssignment,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.GoalID,
	)
	var i ClassroomAssignment
	err := row.Scan(
		&i.ID,
		&i.ClassroomID,
		&i.Title,
		&i.Description,
		&i.GoalID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
