// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classroom.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addClassroomMembership = `-- name: AddClassroomMembership :one
INSERT INTO public.classroom_memberships (classroom_id, user_id, role_in_class, status, joined_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, classroom_id, user_id, role_in_class, status, joined_at, created_at, updated_at
`

type AddClassroomMembershipParams struct {
	ClassroomID uuid.UUID
	UserID      uuid.UUID
	RoleInClass string
	Status      string
	JoinedAt    sql.NullTime
}

func (q *Queries) AddClassroomMembership(ctx context.Context, arg AddClassroomMembershipParams) (ClassroomMembership, error) {
	row := q.db.QueryRowContext(ctx, addClassroomMembership,
		arg.ClassroomID,
		arg.UserID,
		arg.RoleInClass,
		arg.Status,
		arg.JoinedAt,
	)
	var i ClassroomMembership
	err := row.Scan(
		&i.ID,
		&i.ClassroomID,
		&i.UserID,
		&i.RoleInClass,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClassroom = `-- name: CreateClassroom :one
INSERT INTO public.classrooms (owner_id, name, description, invite_code)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, description, invite_code, goal_id, status, created_at, updated_at
`

type CreateClassroomParams struct {
	OwnerID     uuid.UUID
	Name        string
	Description string
	InviteCode  string
}

func (q *Queries) CreateClassroom(ctx context.Context, arg CreateClassroomParams) (Classroom, error) {
	row := q.db.QueryRowContext(ctx, createClassroom,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.InviteCode,
	)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.GoalID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClassroom = `-- name: DeleteClassroom :exec
DELETE FROM public.classrooms WHERE id = $1
`

func (q *Queries) DeleteClassroom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteClassroom, id)
	return err
}

const getClassroomByID = `-- name: GetClassroomByID :one
SELECT id, owner_id, name, description, invite_code, goal_id, status, created_at, updated_at FROM public.classrooms WHERE id = $1
`

func (q *Queries) GetClassroomByID(ctx context.Context, id uuid.UUID) (Classroom, error) {
	row := q.db.QueryRowContext(ctx, getClassroomByID, id)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.GoalID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassroomByInviteCode = `-- name: GetClassroomByInviteCode :one
SELECT id, owner_id, name, description, invite_code, goal_id, status, created_at, updated_at FROM public.classrooms WHERE invite_code = $1 AND status = 'active'
`

func (q *Queries) GetClassroomByInviteCode(ctx context.Context, inviteCode string) (Classroom, error) {
	row := q.db.QueryRowContext(ctx, getClassroomByInviteCode, inviteCode)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.GoalID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipByClassroomAndUser = `-- name: GetMembershipByClassroomAndUser :one
SELECT id, classroom_id, user_id, role_in_class, status, joined_at, created_at, updated_at FROM public.classroom_memberships WHERE classroom_id = $1 AND user_id = $2
`

type GetMembershipByClassroomAndUserParams struct {
	ClassroomID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) GetMembershipByClassroomAndUser(ctx context.Context, arg GetMembershipByClassroomAndUserParams) (ClassroomMembership, error) {
	row := q.db.QueryRowContext(ctx, getMembershipByClassroomAndUser, arg.ClassroomID, arg.UserID)
	var i ClassroomMembership
	err := row.Scan(
		&i.ID,
		&i.ClassroomID,
		&i.UserID,
		&i.RoleInClass,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClassroomsByMember = `-- name: ListClassroomsByMember :many
SELECT c.id, c.owner_id, c.name, c.description, c.invite_code, c.goal_id, c.status, c.created_at, c.updated_at
FROM public.classrooms c
JOIN public.classroom_memberships m ON m.classroom_id = c.id
WHERE m.user_id = $1 AND m.status = 'active'
ORDER BY c.created_at DESC
`

func (q *Queries) ListClassroomsByMember(ctx context.Context, userID uuid.UUID) ([]Classroom, error) {
	rows, err := q.db.QueryContext(ctx, listClassroomsByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Classroom
	for rows.Next() {
		var i Classroom
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.InviteCode,
			&i.GoalID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassroomsByOwner = `-- name: ListClassroomsByOwner :many
SELECT id, owner_id, name, description, invite_code, goal_id, status, created_at, updated_at FROM public.classrooms WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListClassroomsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Classroom, error) {
	rows, err := q.db.QueryContext(ctx, listClassroomsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Classroom
	for rows.Next() {
		var i Classroom
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.InviteCode,
			&i.GoalID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByClassroom = `-- name: ListMembershipsByClassroom :many
SELECT m.id, m.classroom_id, m.user_id, m.role_in_class, m.status, m.joined_at, m.created_at, m.updated_at, u.username, u.email
FROM public.classroom_memberships m
JOIN public.users u ON u.id = m.user_id
WHERE m.classroom_id = $1
ORDER BY m.joined_at ASC
`

type ListMembershipsByClassroomRow struct {
	ID          uuid.UUID
	ClassroomID uuid.UUID
	UserID      uuid.UUID
	RoleInClass string
	Status      string
	JoinedAt    sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Username    string
	Email       string
}

func (q *Queries) ListMembershipsByClassroom(ctx context.Context, classroomID uuid.UUID) ([]ListMembershipsByClassroomRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsByClassroom, classroomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsByClassroomRow
	for rows.Next() {
		var i ListMembershipsByClassroomRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassroomID,
			&i.UserID,
			&i.RoleInClass,
			&i.Status,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClassroom = `-- name: UpdateClassroom :one
UPDATE public.classrooms
SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, owner_id, name, description, invite_code, goal_id, status, created_at, updated_at
`

type UpdateClassroomParams struct {
	ID          uuid.UUID
	Name        string
	Description string
}

func (q *Queries) UpdateClassroom(ctx context.Context, arg UpdateClassroomParams) (Classroom, error) {
	row := q.db.QueryRowContext(ctx, updateClassroom, arg.ID, arg.Name, arg.Description)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.GoalID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClassroomGoal = `-- name: UpdateClassroomGoal :one
UPDATE public.classrooms
SET goal_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, owner_id, name, description, invite_code, goal_id, status, created_at, updated_at
`

type UpdateClassroomGoalParams struct {
	ID     uuid.UUID
	GoalID uuid.NullUUID
}

func (q *Queries) UpdateClassroomGoal(ctx context.Context, arg UpdateClassroomGoalParams) (Classroom, error) {
	row := q.db.QueryRowContext(ctx, updateClassroomGoal, arg.ID, arg.GoalID)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.GoalID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMembershipStatus = `-- name: UpdateMembershipStatus :one
UPDATE public.classroom_memberships
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, classroom_id, user_id, role_in_class, status, joined_at, created_at, updated_at
`

type UpdateMembershipStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (ClassroomMembership, error) {
	row := q.db.QueryRowContext(ctx, updateMembershipStatus, arg.ID, arg.Status)
	var i ClassroomMembership
	err := row.Scan(
		&i.ID,
		&i.ClassroomID,
		&i.UserID,
		&i.RoleInClass,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
