// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_code.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cleanExpiredCodes = `-- name: CleanExpiredCodes :exec
DELETE FROM public.email_codes
WHERE expires_at < now()
`

func (q *Queries) CleanExpiredCodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanExpiredCodes)
	return err
}

const deleteEmailCodeByUserIDAndType = `-- name: DeleteEmailCodeByUserIDAndType :exec
DELETE FROM public.email_codes
WHERE user_id = $1 AND type = $2
`

type DeleteEmailCodeByUserIDAndTypeParams struct {
	UserID uuid.UUID
	Type   string
}

func (q *Queries) DeleteEmailCodeByUserIDAndType(ctx context.Context, arg DeleteEmailCodeByUserIDAndTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmailCodeByUserIDAndType, arg.UserID, arg.Type)
	return err
}

const getEmailCodeByUserIDAndType = `-- name: GetEmailCodeByUserIDAndType :one
SELECT id, user_id, type, code_hash, attempts, max_attempts, expires_at, created_at FROM public.email_codes
WHERE user_id = $1 AND type = $2
`

type GetEmailCodeByUserIDAndTypeParams struct {
	UserID uuid.UUID
	Type   string
}

func (q *Queries) GetEmailCodeByUserIDAndType(ctx context.Context, arg GetEmailCodeByUserIDAndTypeParams) (EmailCode, error) {
	row := q.db.QueryRowContext(ctx, getEmailCodeByUserIDAndType, arg.UserID, arg.Type)
	var i EmailCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.CodeHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertEmailCode = `-- name: UpsertEmailCode :one
INSERT INTO public.email_codes (
    user_id,
    type,
    code_hash,
    attempts,
    max_attempts,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, type) DO UPDATE
SET code_hash = EXCLUDED.code_hash,
    attempts = EXCLUDED.attempts,
    max_attempts = EXCLUDED.max_attempts,
    expires_at = EXCLUDED.expires_at,
    created_at = now()
RETURNING id, user_id, type, code_hash, attempts, max_attempts, expires_at, created_at
`

type UpsertEmailCodeParams struct {
	UserID      uuid.UUID
	Type        string
	CodeHash    string
	Attempts    int32
	MaxAttempts int32
	ExpiresAt   time.Time
}

func (q *Queries) UpsertEmailCode(ctx context.Context, arg UpsertEmailCodeParams) (EmailCode, error) {
	row := q.db.QueryRowContext(ctx, upsertEmailCode,
		arg.UserID,
		arg.Type,
		arg.CodeHash,
		arg.Attempts,
		arg.MaxAttempts,
		arg.ExpiresAt,
	)
	var i EmailCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.CodeHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
