// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_token.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO public.email_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, verified_at, created_at
`

type CreateEmailTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRowContext(ctx, createEmailToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const emailTokenCleanup = `-- name: EmailTokenCleanup :exec
DELETE FROM public.email_tokens
WHERE expires_at < now()
`

func (q *Queries) EmailTokenCleanup(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, emailTokenCleanup)
	return err
}

const getLatestTokenByUserID = `-- name: GetLatestTokenByUserID :one
SELECT id, user_id, token_hash, expires_at, verified_at, created_at FROM public.email_tokens
WHERE user_id = $1
    AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestTokenByUserID(ctx context.Context, userID uuid.UUID) (EmailToken, error) {
	row := q.db.QueryRowContext(ctx, getLatestTokenByUserID, userID)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const verifyTokenByHash = `-- name: VerifyTokenByHash :one
UPDATE public.email_tokens
SET verified_at = now()
WHERE token_hash = $1
    AND expires_at > now()
    AND verified_at IS NULL
    RETURNING id, user_id, token_hash, expires_at, verified_at, created_at
`

func (q *Queries) VerifyTokenByHash(ctx context.Context, tokenHash string) (EmailToken, error) {
	row := q.db.QueryRowContext(ctx, verifyTokenByHash, tokenHash)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}
