// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flashcard.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createFlashcard = `-- name: CreateFlashcard :one
INSERT INTO public.flashcards (user_id, topic_id, source, front, back)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, topic_id, source, front, back, created_at, updated_at
`

type CreateFlashcardParams struct {
	UserID  uuid.NullUUID
	TopicID uuid.UUID
	Source  FlashcardSource
	Front   string
	Back    string
}

func (q *Queries) CreateFlashcard(ctx context.Context, arg CreateFlashcardParams) (Flashcard, error) {
	row := q.db.QueryRowContext(ctx, createFlashcard,
		arg.UserID,
		arg.TopicID,
		arg.Source,
		arg.Front,
		arg.Back,
	)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicID,
		&i.Source,
		&i.Front,
		&i.Back,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlashcardProgress = `-- name: CreateFlashcardProgress :one
INSERT INTO public.flashcard_progress (user_id, flashcard_id, ease_factor, interval_days, repetitions, next_review_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, flashcard_id, ease_factor, interval_days, repetitions, next_review_at, last_reviewed_at, created_at, updated_at
`

type CreateFlashcardProgressParams struct {
	UserID       uuid.UUID
	FlashcardID  uuid.UUID
	EaseFactor   float64
	IntervalDays int32
	Repetitions  int32
	NextReviewAt time.Time
}

func (q *Queries) CreateFlashcardProgress(ctx context.Context, arg CreateFlashcardProgressParams) (FlashcardProgress, error) {
	row := q.db.QueryRowContext(ctx, createFlashcardProgress,
		arg.UserID,
		arg.FlashcardID,
		arg.EaseFactor,
		arg.IntervalDays,
		arg.Repetitions,
		arg.NextReviewAt,
	)
	var i FlashcardProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FlashcardID,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReviewAt,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlashcard = `-- name: DeleteFlashcard :exec
DELETE FROM public.flashcards WHERE id = $1
`

func (q *Queries) DeleteFlashcard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFlashcard, id)
	return err
}

const getFlashcardByID = `-- name: GetFlashcardByID :one
SELECT id, user_id, topic_id, source, front, back, created_at, updated_at FROM public.flashcards WHERE id = $1
`

func (q *Queries) GetFlashcardByID(ctx context.Context, id uuid.UUID) (Flashcard, error) {
	row := q.db.QueryRowContext(ctx, getFlashcardByID, id)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicID,
		&i.Source,
		&i.Front,
		&i.Back,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlashcardProgressByUserAndCard = `-- name: GetFlashcardProgressByUserAndCard :one
SELECT id, user_id, flashcard_id, ease_factor, interval_days, repetitions, next_review_at, last_reviewed_at, created_at, updated_at FROM public.flashcard_progress WHERE user_id = $1 AND flashcard_id = $2
`

type GetFlashcardProgressByUserAndCardParams struct {
	UserID      uuid.UUID
	FlashcardID uuid.UUID
}

func (q *Queries) GetFlashcardProgressByUserAndCard(ctx context.Context, arg GetFlashcardProgressByUserAndCardParams) (FlashcardProgress, error) {
	row := q.db.QueryRowContext(ctx, getFlashcardProgressByUserAndCard, arg.UserID, arg.FlashcardID)
	var i FlashcardProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FlashcardID,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReviewAt,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardProgressByUserAndTopic = `-- name: ListCardProgressByUserAndTopic :many
SELECT f.id AS flashcard_id, f.topic_id, f.source, f.front, f.back, f.created_at AS flashcard_created_at,
       p.id AS progress_id, p.ease_factor, p.interval_days, p.repetitions, p.next_review_at, p.last_reviewed_at
FROM public.flashcards f
LEFT JOIN public.flashcard_progress p ON p.flashcard_id = f.id AND p.user_id = $1
WHERE f.topic_id = $2
ORDER BY f.created_at DESC
`

type ListCardProgressByUserAndTopicParams struct {
	UserID  uuid.UUID
	TopicID uuid.UUID
}

type ListCardProgressByUserAndTopicRow struct {
	FlashcardID        uuid.UUID
	TopicID            uuid.UUID
	Source             FlashcardSource
	Front              string
	Back               string
	FlashcardCreatedAt time.Time
	ProgressID         uuid.NullUUID
	EaseFactor         sql.NullString
	IntervalDays       sql.NullInt32
	Repetitions        sql.NullInt32
	NextReviewAt       sql.NullTime
	LastReviewedAt     sql.NullTime
}

func (q *Queries) ListCardProgressByUserAndTopic(ctx context.Context, arg ListCardProgressByUserAndTopicParams) ([]ListCardProgressByUserAndTopicRow, error) {
	rows, err := q.db.QueryContext(ctx, listCardProgressByUserAndTopic, arg.UserID, arg.TopicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardProgressByUserAndTopicRow
	for rows.Next() {
		var i ListCardProgressByUserAndTopicRow
		if err := rows.Scan(
			&i.FlashcardID,
			&i.TopicID,
			&i.Source,
			&i.Front,
			&i.Back,
			&i.FlashcardCreatedAt,
			&i.ProgressID,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.NextReviewAt,
			&i.LastReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueFlashcardProgressByTopicIDs = `-- name: ListDueFlashcardProgressByTopicIDs :many
SELECT p.id, p.user_id, p.flashcard_id, p.ease_factor, p.interval_days, p.repetitions, p.next_review_at, p.last_reviewed_at, p.created_at, p.updated_at, f.topic_id, f.front, f.back, f.source
FROM public.flashcard_progress p
JOIN public.flashcards f ON f.id = p.flashcard_id
WHERE p.user_id = $1
  AND f.topic_id = ANY($2::uuid[])
  AND p.next_review_at <= now()
ORDER BY p.next_review_at ASC
LIMIT $3
`

type ListDueFlashcardProgressByTopicIDsParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
	Limit   int32
}

type ListDueFlashcardProgressByTopicIDsRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	FlashcardID    uuid.UUID
	EaseFactor     float64
	IntervalDays   int32
	Repetitions    int32
	NextReviewAt   time.Time
	LastReviewedAt sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
	TopicID        uuid.UUID
	Front          string
	Back           string
	Source         FlashcardSource
}

func (q *Queries) ListDueFlashcardProgressByTopicIDs(ctx context.Context, arg ListDueFlashcardProgressByTopicIDsParams) ([]ListDueFlashcardProgressByTopicIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueFlashcardProgressByTopicIDs, arg.UserID, pq.Array(arg.Column2), arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueFlashcardProgressByTopicIDsRow
	for rows.Next() {
		var i ListDueFlashcardProgressByTopicIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FlashcardID,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.NextReviewAt,
			&i.LastReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TopicID,
			&i.Front,
			&i.Back,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueFlashcardProgressByUser = `-- name: ListDueFlashcardProgressByUser :many
SELECT p.id, p.user_id, p.flashcard_id, p.ease_factor, p.interval_days, p.repetitions, p.next_review_at, p.last_reviewed_at, p.created_at, p.updated_at, f.topic_id, f.front, f.back, f.source
FROM public.flashcard_progress p
JOIN public.flashcards f ON f.id = p.flashcard_id
WHERE p.user_id = $1 AND p.next_review_at <= now()
ORDER BY p.next_review_at ASC
LIMIT $2
`

type ListDueFlashcardProgressByUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

type ListDueFlashcardProgressByUserRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	FlashcardID    uuid.UUID
	EaseFactor     float64
	IntervalDays   int32
	Repetitions    int32
	NextReviewAt   time.Time
	LastReviewedAt sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
	TopicID        uuid.UUID
	Front          string
	Back           string
	Source         FlashcardSource
}

func (q *Queries) ListDueFlashcardProgressByUser(ctx context.Context, arg ListDueFlashcardProgressByUserParams) ([]ListDueFlashcardProgressByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueFlashcardProgressByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueFlashcardProgressByUserRow
	for rows.Next() {
		var i ListDueFlashcardProgressByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FlashcardID,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.NextReviewAt,
			&i.LastReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TopicID,
			&i.Front,
			&i.Back,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlashcardsByTopic = `-- name: ListFlashcardsByTopic :many
SELECT id, user_id, topic_id, source, front, back, created_at, updated_at FROM public.flashcards WHERE topic_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListFlashcardsByTopic(ctx context.Context, topicID uuid.UUID) ([]Flashcard, error) {
	rows, err := q.db.QueryContext(ctx, listFlashcardsByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flashcard
	for rows.Next() {
		var i Flashcard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TopicID,
			&i.Source,
			&i.Front,
			&i.Back,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlashcard = `-- name: UpdateFlashcard :one
UPDATE public.flashcards
SET front = $2, back = $3, updated_at = now()
WHERE id = $1
RETURNING id, user_id, topic_id, source, front, back, created_at, updated_at
`

type UpdateFlashcardParams struct {
	ID    uuid.UUID
	Front string
	Back  string
}

func (q *Queries) UpdateFlashcard(ctx context.Context, arg UpdateFlashcardParams) (Flashcard, error) {
	row := q.db.QueryRowContext(ctx, updateFlashcard, arg.ID, arg.Front, arg.Back)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicID,
		&i.Source,
		&i.Front,
		&i.Back,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlashcardProgress = `-- name: UpdateFlashcardProgress :one
UPDATE public.flashcard_progress
SET ease_factor = $2,
    interval_days = $3,
    repetitions = $4,
    next_review_at = $5,
    last_reviewed_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, flashcard_id, ease_factor, interval_days, repetitions, next_review_at, last_reviewed_at, created_at, updated_at
`

type UpdateFlashcardProgressParams struct {
	ID           uuid.UUID
	EaseFactor   float64
	IntervalDays int32
	Repetitions  int32
	NextReviewAt time.Time
}

func (q *Queries) UpdateFlashcardProgress(ctx context.Context, arg UpdateFlashcardProgressParams) (FlashcardProgress, error) {
	row := q.db.QueryRowContext(ctx, updateFlashcardProgress,
		arg.ID,
		arg.EaseFactor,
		arg.IntervalDays,
		arg.Repetitions,
		arg.NextReviewAt,
	)
	var i FlashcardProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FlashcardID,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReviewAt,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
