// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friend.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO public.friendships (user_id, friend_id)
VALUES ($1, $2)
RETURNING id, user_id, friend_id, created_at
`

type CreateFriendshipParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, createFriendship, arg.UserID, arg.FriendID)
	var i Friendship
	err := row.Scan(&i.ID, &i.UserID, &i.FriendID, &i.CreatedAt)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM public.friendships
WHERE user_id = $1 AND friend_id = $2
`

type DeleteFriendshipParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendship, arg.UserID, arg.FriendID)
	return err
}

const countFriendshipsByUser = `-- name: CountFriendshipsByUser :one
SELECT count(*) FROM public.friendships
WHERE user_id = $1
`

func (q *Queries) CountFriendshipsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFriendshipsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, user_id, friend_id, created_at FROM public.friendships
WHERE user_id = $1 AND friend_id = $2
`

type GetFriendshipParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, getFriendship, arg.UserID, arg.FriendID)
	var i Friendship
	err := row.Scan(&i.ID, &i.UserID, &i.FriendID, &i.CreatedAt)
	return i, err
}

const listFriendshipsWithProfile = `-- name: ListFriendshipsWithProfile :many
SELECT
    f.id,
    f.created_at,
    u.id AS friend_id,
    u.username,
    u.created_at AS friend_since,
    COALESCE(p.avatar_url, '') AS avatar_url,
    COALESCE(p.xp, 0) AS xp,
    COALESCE(p.streak, 0) AS streak,
    p.last_activity_date
FROM public.friendships f
JOIN public.users u ON u.id = f.friend_id
LEFT JOIN public.profile p ON p.user_id = u.id
WHERE f.user_id = $1
ORDER BY f.created_at DESC
`

type ListFriendshipsWithProfileRow struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	FriendID         uuid.UUID
	Username         string
	FriendSince      time.Time
	AvatarUrl        string
	Xp               int32
	Streak           int32
	LastActivityDate sql.NullTime
}

func (q *Queries) ListFriendshipsWithProfile(ctx context.Context, userID uuid.UUID) ([]ListFriendshipsWithProfileRow, error) {
	rows, err := q.db.QueryContext(ctx, listFriendshipsWithProfile, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFriendshipsWithProfileRow{}
	for rows.Next() {
		var i ListFriendshipsWithProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.FriendID,
			&i.Username,
			&i.FriendSince,
			&i.AvatarUrl,
			&i.Xp,
			&i.Streak,
			&i.LastActivityDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByEmailOrUsername = `-- name: SearchUsersByEmailOrUsername :many
SELECT id, username, email, password_hash, verified, created_at, role FROM public.users
WHERE lower(email) = lower($1)
   OR lower(username) = lower($2)
ORDER BY created_at ASC
LIMIT 5
`

type SearchUsersByEmailOrUsernameParams struct {
	Email    string
	Username string
}

func (q *Queries) SearchUsersByEmailOrUsername(ctx context.Context, arg SearchUsersByEmailOrUsernameParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersByEmailOrUsername, arg.Email, arg.Username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Verified,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersForFriends = `-- name: SearchUsersForFriends :many
SELECT
    u.id,
    u.username,
    COALESCE(p.avatar_url, '') AS avatar_url,
    COALESCE(p.xp, 0) AS xp,
    COALESCE(p.streak, 0) AS streak,
    EXISTS (
        SELECT 1 FROM public.friendships f
        WHERE f.user_id = $1 AND f.friend_id = u.id
    ) AS is_friend
FROM public.users u
LEFT JOIN public.profile p ON p.user_id = u.id
WHERE u.id <> $1
  AND (lower(u.username) LIKE lower('%' || $2 || '%')
       OR lower(u.email) LIKE lower('%' || $2 || '%'))
ORDER BY is_friend DESC, u.username ASC
LIMIT 8
`

type SearchUsersForFriendsParams struct {
	RequesterID uuid.UUID
	Term        string
}

type SearchUsersForFriendsRow struct {
	ID        uuid.UUID
	Username  string
	AvatarUrl string
	Xp        int32
	Streak    int32
	IsFriend  bool
}

func (q *Queries) SearchUsersForFriends(ctx context.Context, arg SearchUsersForFriendsParams) ([]SearchUsersForFriendsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersForFriends, arg.RequesterID, arg.Term)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersForFriendsRow{}
	for rows.Next() {
		var i SearchUsersForFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.Xp,
			&i.Streak,
			&i.IsFriend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
