// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type EmailCode struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	CodeHash    string
	Attempts    int32
	MaxAttempts int32
	ExpiresAt   time.Time
	CreatedAt   time.Time
}

type Goal struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Title        string
	Difficulties json.RawMessage
	CreatedAt    time.Time
}

type OauthAccount struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	CreatedAt      time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
	Revoked   bool
	RevokedAt sql.NullTime
	CreatedAt sql.NullTime
}

type Task struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	GoalID    uuid.UUID
	Content   json.RawMessage
	Type      string
	Done      bool
	DoneAt    sql.NullTime
	CreatedAt sql.NullTime
}

type TaskAttempt struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	TaskID         uuid.UUID
	Content        json.RawMessage
	Score          sql.NullString
	Status         sql.NullString
	TaskEvaluation json.RawMessage
	CreatedAt      sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash sql.NullString
	Verified     bool
	CreatedAt    time.Time
}
