// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type TopicStatus string

const (
	TopicStatusLOCKED     TopicStatus = "LOCKED"
	TopicStatusAVAILABLE  TopicStatus = "AVAILABLE"
	TopicStatusINPROGRESS TopicStatus = "IN_PROGRESS"
	TopicStatusMASTERED   TopicStatus = "MASTERED"
)

func (e *TopicStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TopicStatus(s)
	case string:
		*e = TopicStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TopicStatus: %T", src)
	}
	return nil
}

type NullTopicStatus struct {
	TopicStatus TopicStatus
	Valid       bool // Valid is true if TopicStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTopicStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TopicStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TopicStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTopicStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TopicStatus), nil
}

type EmailCode struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	CodeHash    string
	Attempts    int32
	MaxAttempts int32
	ExpiresAt   time.Time
	CreatedAt   time.Time
}

type Goal struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Settings  json.RawMessage
	CreatedAt time.Time
}

type OauthAccount struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	CreatedAt      time.Time
}

type Profile struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Xp               int32
	Streak           int32
	LastActivityDate time.Time
	AvatarUrl        sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
	Revoked   bool
	RevokedAt sql.NullTime
	CreatedAt sql.NullTime
}

type Task struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Content   json.RawMessage
	Type      string
	Done      bool
	DoneAt    sql.NullTime
	CreatedAt sql.NullTime
	TopicID   uuid.UUID
}

type TaskAttempt struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	TaskID         uuid.UUID
	Content        json.RawMessage
	Score          sql.NullString
	Status         sql.NullString
	TaskEvaluation json.RawMessage
	CreatedAt      sql.NullTime
}

type TaskCorrection struct {
	ID        uuid.UUID
	AttemptID uuid.UUID
	Feedback  string
	Score     sql.NullString
	Status    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Topic struct {
	ID              uuid.UUID
	GoalID          uuid.UUID
	ParentTopicID   uuid.NullUUID
	Title           string
	Description     string
	RequiredMastery float64
	Weight          float64
	OrderIndex      int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TopicDependency struct {
	ID               uuid.UUID
	TopicID          uuid.UUID
	DependsOnTopicID uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type TopicProgress struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	TopicID         uuid.UUID
	MasteryScore    float64
	ConfidenceScore float64
	AttemptsCount   int32
	Status          TopicStatus
	CreatedAt       time.Time
	UpdatedAt       time.Time
	EvolutionStage  string
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash sql.NullString
	Verified     bool
	CreatedAt    time.Time
}
