// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profile (id, user_id, xp, streak, last_activity_date, avatar_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, xp, streak, last_activity_date, avatar_url, created_at, updated_at
`

type CreateProfileParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Xp               int32
	Streak           int32
	LastActivityDate time.Time
	AvatarUrl        sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.ID,
		arg.UserID,
		arg.Xp,
		arg.Streak,
		arg.LastActivityDate,
		arg.AvatarUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Xp,
		&i.Streak,
		&i.LastActivityDate,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, xp, streak, last_activity_date, avatar_url, created_at, updated_at FROM profile WHERE user_id = $1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Xp,
		&i.Streak,
		&i.LastActivityDate,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profile SET xp = $2, streak = $3, last_activity_date = $4, avatar_url = $5, updated_at = $6 WHERE id = $1
RETURNING id, user_id, xp, streak, last_activity_date, avatar_url, created_at, updated_at
`

type UpdateProfileParams struct {
	ID               uuid.UUID
	Xp               int32
	Streak           int32
	LastActivityDate time.Time
	AvatarUrl        sql.NullString
	UpdatedAt        time.Time
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.ID,
		arg.Xp,
		arg.Streak,
		arg.LastActivityDate,
		arg.AvatarUrl,
		arg.UpdatedAt,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Xp,
		&i.Streak,
		&i.LastActivityDate,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
