// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_corrections.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTaskCorrection = `-- name: CreateTaskCorrection :one
INSERT INTO task_corrections (attempt_id, feedback, score, status)
VALUES ($1, $2, $3, $4)
RETURNING id, attempt_id, feedback, score, status, created_at, updated_at
`

type CreateTaskCorrectionParams struct {
	AttemptID uuid.UUID
	Feedback  string
	Score     sql.NullString
	Status    string
}

func (q *Queries) CreateTaskCorrection(ctx context.Context, arg CreateTaskCorrectionParams) (TaskCorrection, error) {
	row := q.db.QueryRowContext(ctx, createTaskCorrection,
		arg.AttemptID,
		arg.Feedback,
		arg.Score,
		arg.Status,
	)
	var i TaskCorrection
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.Feedback,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskCorrectionByAttemptID = `-- name: GetTaskCorrectionByAttemptID :one
SELECT id, attempt_id, feedback, score, status, created_at, updated_at
FROM task_corrections
WHERE attempt_id = $1
`

func (q *Queries) GetTaskCorrectionByAttemptID(ctx context.Context, attemptID uuid.UUID) (TaskCorrection, error) {
	row := q.db.QueryRowContext(ctx, getTaskCorrectionByAttemptID, attemptID)
	var i TaskCorrection
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.Feedback,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskCorrectionByID = `-- name: GetTaskCorrectionByID :one
SELECT id, attempt_id, feedback, score, status, created_at, updated_at
FROM task_corrections
WHERE id = $1
`

func (q *Queries) GetTaskCorrectionByID(ctx context.Context, id uuid.UUID) (TaskCorrection, error) {
	row := q.db.QueryRowContext(ctx, getTaskCorrectionByID, id)
	var i TaskCorrection
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.Feedback,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskCorrection = `-- name: UpdateTaskCorrection :one
UPDATE task_corrections
SET feedback = $2,
    score = $3,
    status = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, attempt_id, feedback, score, status, created_at, updated_at
`

type UpdateTaskCorrectionParams struct {
	ID       uuid.UUID
	Feedback string
	Score    sql.NullString
	Status   string
}

func (q *Queries) UpdateTaskCorrection(ctx context.Context, arg UpdateTaskCorrectionParams) (TaskCorrection, error) {
	row := q.db.QueryRowContext(ctx, updateTaskCorrection,
		arg.ID,
		arg.Feedback,
		arg.Score,
		arg.Status,
	)
	var i TaskCorrection
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.Feedback,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
