// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_attempts.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createTaskAttempt = `-- name: CreateTaskAttempt :one
INSERT INTO task_attempts (user_id, task_id, content, score, status, task_evaluation)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, task_id, content, score, status, task_evaluation, created_at
`

type CreateTaskAttemptParams struct {
	UserID         uuid.UUID
	TaskID         uuid.UUID
	Content        json.RawMessage
	Score          sql.NullString
	Status         sql.NullString
	TaskEvaluation json.RawMessage
}

func (q *Queries) CreateTaskAttempt(ctx context.Context, arg CreateTaskAttemptParams) (TaskAttempt, error) {
	row := q.db.QueryRowContext(ctx, createTaskAttempt,
		arg.UserID,
		arg.TaskID,
		arg.Content,
		arg.Score,
		arg.Status,
		arg.TaskEvaluation,
	)
	var i TaskAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Content,
		&i.Score,
		&i.Status,
		&i.TaskEvaluation,
		&i.CreatedAt,
	)
	return i, err
}

const getLastTaskAttempt = `-- name: GetLastTaskAttempt :one
SELECT id, user_id, task_id, content, score, status, task_evaluation, created_at
FROM task_attempts
WHERE user_id = $1
  AND task_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLastTaskAttemptParams struct {
	UserID uuid.UUID
	TaskID uuid.UUID
}

func (q *Queries) GetLastTaskAttempt(ctx context.Context, arg GetLastTaskAttemptParams) (TaskAttempt, error) {
	row := q.db.QueryRowContext(ctx, getLastTaskAttempt, arg.UserID, arg.TaskID)
	var i TaskAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Content,
		&i.Score,
		&i.Status,
		&i.TaskEvaluation,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskAttemptByID = `-- name: GetTaskAttemptByID :one
SELECT id, user_id, task_id, content, score, status, task_evaluation, created_at
FROM task_attempts
WHERE id = $1
`

func (q *Queries) GetTaskAttemptByID(ctx context.Context, id uuid.UUID) (TaskAttempt, error) {
	row := q.db.QueryRowContext(ctx, getTaskAttemptByID, id)
	var i TaskAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Content,
		&i.Score,
		&i.Status,
		&i.TaskEvaluation,
		&i.CreatedAt,
	)
	return i, err
}

const listTaskAttemptsByUser = `-- name: ListTaskAttemptsByUser :many
SELECT id, user_id, task_id, content, score, status, task_evaluation, created_at
FROM task_attempts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTaskAttemptsByUser(ctx context.Context, userID uuid.UUID) ([]TaskAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listTaskAttemptsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskAttempt
	for rows.Next() {
		var i TaskAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Content,
			&i.Score,
			&i.Status,
			&i.TaskEvaluation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAttemptsByUserAndTask = `-- name: ListTaskAttemptsByUserAndTask :many
SELECT id, user_id, task_id, content, score, status, task_evaluation, created_at
FROM task_attempts
WHERE user_id = $1
  AND task_id = $2
ORDER BY created_at DESC
`

type ListTaskAttemptsByUserAndTaskParams struct {
	UserID uuid.UUID
	TaskID uuid.UUID
}

func (q *Queries) ListTaskAttemptsByUserAndTask(ctx context.Context, arg ListTaskAttemptsByUserAndTaskParams) ([]TaskAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listTaskAttemptsByUserAndTask, arg.UserID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskAttempt
	for rows.Next() {
		var i TaskAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Content,
			&i.Score,
			&i.Status,
			&i.TaskEvaluation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
