// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic_dependency.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTopicDependency = `-- name: CreateTopicDependency :one
INSERT INTO public.topic_dependencies (topic_id, depends_on_topic_id)
VALUES ($1, $2)
RETURNING id, topic_id, depends_on_topic_id, created_at, updated_at
`

type CreateTopicDependencyParams struct {
	TopicID          uuid.UUID
	DependsOnTopicID uuid.UUID
}

func (q *Queries) CreateTopicDependency(ctx context.Context, arg CreateTopicDependencyParams) (TopicDependency, error) {
	row := q.db.QueryRowContext(ctx, createTopicDependency, arg.TopicID, arg.DependsOnTopicID)
	var i TopicDependency
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.DependsOnTopicID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
