// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO public.topics (goal_id, parent_topic_id, title, description, required_mastery, weight, order_index)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, goal_id, parent_topic_id, title, description, required_mastery, weight, order_index, created_at, updated_at
`

type CreateTopicParams struct {
	GoalID          uuid.UUID
	ParentTopicID   uuid.NullUUID
	Title           string
	Description     string
	RequiredMastery float64
	Weight          float64
	OrderIndex      int32
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRowContext(ctx, createTopic,
		arg.GoalID,
		arg.ParentTopicID,
		arg.Title,
		arg.Description,
		arg.RequiredMastery,
		arg.Weight,
		arg.OrderIndex,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.ParentTopicID,
		&i.Title,
		&i.Description,
		&i.RequiredMastery,
		&i.Weight,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTopicsByGoalID = `-- name: DeleteTopicsByGoalID :exec
DELETE FROM public.topics
WHERE goal_id = $1
`

func (q *Queries) DeleteTopicsByGoalID(ctx context.Context, goalID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTopicsByGoalID, goalID)
	return err
}

const getTopicByGoalID = `-- name: GetTopicByGoalID :many
SELECT id, goal_id, parent_topic_id, title, description, required_mastery, weight, order_index, created_at, updated_at FROM public.topics
WHERE goal_id = $1
`

func (q *Queries) GetTopicByGoalID(ctx context.Context, goalID uuid.UUID) ([]Topic, error) {
	rows, err := q.db.QueryContext(ctx, getTopicByGoalID, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.ParentTopicID,
			&i.Title,
			&i.Description,
			&i.RequiredMastery,
			&i.Weight,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT id, goal_id, parent_topic_id, title, description, required_mastery, weight, order_index, created_at, updated_at FROM public.topics
WHERE id = $1
`

func (q *Queries) GetTopicByID(ctx context.Context, id uuid.UUID) (Topic, error) {
	row := q.db.QueryRowContext(ctx, getTopicByID, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.ParentTopicID,
		&i.Title,
		&i.Description,
		&i.RequiredMastery,
		&i.Weight,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
