// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic_progress.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTopicProgress = `-- name: CreateTopicProgress :one
INSERT INTO public.topic_progress (user_id, topic_id, mastery_score, confidence_score, attempts_count, status, evolution_stage)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, topic_id, mastery_score, confidence_score, attempts_count, status, evolution_stage, created_at, updated_at
`

type CreateTopicProgressParams struct {
	UserID          uuid.UUID
	TopicID         uuid.UUID
	MasteryScore    float64
	ConfidenceScore float64
	AttemptsCount   int32
	Status          TopicStatus
	EvolutionStage  string
}

type CreateTopicProgressRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	TopicID         uuid.UUID
	MasteryScore    float64
	ConfidenceScore float64
	AttemptsCount   int32
	Status          TopicStatus
	EvolutionStage  string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateTopicProgress(ctx context.Context, arg CreateTopicProgressParams) (CreateTopicProgressRow, error) {
	row := q.db.QueryRowContext(ctx, createTopicProgress,
		arg.UserID,
		arg.TopicID,
		arg.MasteryScore,
		arg.ConfidenceScore,
		arg.AttemptsCount,
		arg.Status,
		arg.EvolutionStage,
	)
	var i CreateTopicProgressRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicID,
		&i.MasteryScore,
		&i.ConfidenceScore,
		&i.AttemptsCount,
		&i.Status,
		&i.EvolutionStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopicProgressByUserIDAndTopicID = `-- name: GetTopicProgressByUserIDAndTopicID :one
SELECT id, user_id, topic_id, mastery_score, confidence_score, attempts_count, status, evolution_stage, created_at, updated_at
FROM public.topic_progress
WHERE user_id = $1 AND topic_id = $2
`

type GetTopicProgressByUserIDAndTopicIDParams struct {
	UserID  uuid.UUID
	TopicID uuid.UUID
}

type GetTopicProgressByUserIDAndTopicIDRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	TopicID         uuid.UUID
	MasteryScore    float64
	ConfidenceScore float64
	AttemptsCount   int32
	Status          TopicStatus
	EvolutionStage  string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetTopicProgressByUserIDAndTopicID(ctx context.Context, arg GetTopicProgressByUserIDAndTopicIDParams) (GetTopicProgressByUserIDAndTopicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTopicProgressByUserIDAndTopicID, arg.UserID, arg.TopicID)
	var i GetTopicProgressByUserIDAndTopicIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicID,
		&i.MasteryScore,
		&i.ConfidenceScore,
		&i.AttemptsCount,
		&i.Status,
		&i.EvolutionStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTopicProgress = `-- name: UpdateTopicProgress :one
UPDATE public.topic_progress
SET mastery_score = $2, confidence_score = $3, attempts_count = $4, status = $5, evolution_stage = $6, updated_at = now()
WHERE id = $1
RETURNING id, user_id, topic_id, mastery_score, confidence_score, attempts_count, status, evolution_stage, created_at, updated_at
`

type UpdateTopicProgressParams struct {
	ID              uuid.UUID
	MasteryScore    float64
	ConfidenceScore float64
	AttemptsCount   int32
	Status          TopicStatus
	EvolutionStage  string
}

type UpdateTopicProgressRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	TopicID         uuid.UUID
	MasteryScore    float64
	ConfidenceScore float64
	AttemptsCount   int32
	Status          TopicStatus
	EvolutionStage  string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) UpdateTopicProgress(ctx context.Context, arg UpdateTopicProgressParams) (UpdateTopicProgressRow, error) {
	row := q.db.QueryRowContext(ctx, updateTopicProgress,
		arg.ID,
		arg.MasteryScore,
		arg.ConfidenceScore,
		arg.AttemptsCount,
		arg.Status,
		arg.EvolutionStage,
	)
	var i UpdateTopicProgressRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TopicID,
		&i.MasteryScore,
		&i.ConfidenceScore,
		&i.AttemptsCount,
		&i.Status,
		&i.EvolutionStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopicProgressByUserIDAndGoalID = `-- name: GetTopicProgressByUserIDAndGoalID :many
SELECT tp.id, tp.user_id, tp.topic_id, tp.mastery_score, tp.confidence_score, tp.attempts_count, tp.status, tp.evolution_stage, tp.created_at, tp.updated_at
FROM public.topic_progress tp
JOIN public.topics t ON t.id = tp.topic_id
WHERE tp.user_id = $1 AND t.goal_id = $2
`

type GetTopicProgressByUserIDAndGoalIDParams struct {
	UserID uuid.UUID
	GoalID uuid.UUID
}

func (q *Queries) GetTopicProgressByUserIDAndGoalID(ctx context.Context, arg GetTopicProgressByUserIDAndGoalIDParams) ([]TopicProgress, error) {
	rows, err := q.db.QueryContext(ctx, getTopicProgressByUserIDAndGoalID, arg.UserID, arg.GoalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopicProgress
	for rows.Next() {
		var i TopicProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TopicID,
			&i.MasteryScore,
			&i.ConfidenceScore,
			&i.AttemptsCount,
			&i.Status,
			&i.EvolutionStage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
