// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOneUser = `-- name: CreateOneUser :one
INSERT INTO public.users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, verified, created_at
`

type CreateOneUserParams struct {
	Username     string
	Email        string
	PasswordHash sql.NullString
}

func (q *Queries) CreateOneUser(ctx context.Context, arg CreateOneUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createOneUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :one
DELETE FROM public.users
WHERE email = $1
RETURNING id
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteUserByEmail, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, verified, created_at
FROM public.users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, verified, created_at
FROM public.users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPasswordByID = `-- name: UpdateUserPasswordByID :exec
UPDATE public.users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordByIDParams struct {
	ID           uuid.UUID
	PasswordHash sql.NullString
}

func (q *Queries) UpdateUserPasswordByID(ctx context.Context, arg UpdateUserPasswordByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordByID, arg.ID, arg.PasswordHash)
	return err
}

const verifyUserByID = `-- name: VerifyUserByID :exec
UPDATE public.users
SET verified = true
WHERE id = $1
`

func (q *Queries) VerifyUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, verifyUserByID, id)
	return err
}
