$kind: http-request
name: Generate Tasks for Goal
method: POST
url: '{{backendBaseUrl}}/protected/tasks/generate'
order: 1000
headers:
  - key: Content-Type
    value: application/json
  - key: Accept
    value: application/json
auth:
  type: bearer
  credentials:
    - key: token
      value: '{{accessToken}}'
body:
  type: json
  content: |-
    {
      "goal_id": "{{goalId}}"
    }
