$kind: http-request
name: List Tasks
method: GET
url: '{{backendBaseUrl}}/protected/tasks'
order: 2000
headers:
  - key: Accept
    value: application/json
auth:
  type: bearer
  credentials:
    - key: token
      value: '{{accessToken}}'
